"""add tables with foreign keys

Revision ID: d261da58cf5c
Revises: 1cef6bba258f
Create Date: 2025-06-01 19:37:59.258395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd261da58cf5c'
down_revision: Union[str, None] = '1cef6bba258f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'customer_id')
    # ### end Alembic commands ###
