"""add tracking dimensions and product groups

Revision ID: d2afedf4efb1
Revises: d261da58cf5c
Create Date: 2025-06-08 14:22:41.127781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2afedf4efb1'
down_revision: Union[str, None] = 'd261da58cf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tracking_dimensions_id'), 'tracking_dimensions', ['id'], unique=False)
    op.create_table('product_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tracking_dimension_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_dimension_id'], ['tracking_dimensions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_groups_id'), 'product_groups', ['id'], unique=False)
    op.create_table('product_serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_product_serials_id'), 'product_serials', ['id'], unique=False)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.drop_index(op.f('ix_product_serials_id'), table_name='product_serials')
    op.drop_table('product_serials')
    op.drop_index(op.f('ix_product_groups_id'), table_name='product_groups')
    op.drop_table('product_groups')
    op.drop_index(op.f('ix_tracking_dimensions_id'), table_name='tracking_dimensions')
    op.drop_table('tracking_dimensions')
    # ### end Alembic commands ###
